// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Category: typeof import('./src/components/chart/Category.vue')['default']
    DailyInfo: typeof import('./src/components/info/DailyInfo.vue')['default']
    Login: typeof import('./src/components/users/login.vue')['default']
    MapView: typeof import('./src/components/map/MapView.vue')['default']
    New: typeof import('./src/components/New.vue')['default']
    ProvinceInfo: typeof import('./src/components/info/ProvinceInfo.vue')['default']
    ProvinceMapView: typeof import('./src/components/map/ProvinceMapView.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Rumors: typeof import('./src/components/Rumors.vue')['default']
    StackedLine: typeof import('./src/components/chart/StackedLine.vue')['default']
    TabView: typeof import('./src/components/TabView.vue')['default']
    WorldMapView: typeof import('./src/components/map/WorldMapView.vue')['default']
    WroldInfo: typeof import('./src/components/info/WroldInfo.vue')['default']
  }
}
