// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
<<<<<<< HEAD
    DailyInfo: typeof import('./src/components/info/DailyInfo.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    InfoBar: typeof import('./src/components/bar chart/infoBar.vue')['default']
    InfoSwipe: typeof import('./src/components/InfoSwipe.vue')['default']
    Login: typeof import('./src/components/users/login.vue')['default']
    MapView: typeof import('./src/components/map/MapView.vue')['default']
    New: typeof import('./src/components/New.vue')['default']
    ProvinceInfo: typeof import('./src/components/info/ProvinceInfo.vue')['default']
=======
    CityActive: typeof import('./src/components/bar chart/CityActive.vue')['default']
    CityImported: typeof import('./src/components/bar chart/CityImported.vue')['default']
    DailyInfo: typeof import('./src/components/DailyInfo.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    InfoSwipe: typeof import('./src/components/InfoSwipe.vue')['default']
    MapView: typeof import('./src/components/map/MapView.vue')['default']
    New: typeof import('./src/components/New.vue')['default']
>>>>>>> fe33b65b667055bd0d038682577754640267fcd6
    ProvinceMapView: typeof import('./src/components/map/ProvinceMapView.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TabView: typeof import('./src/components/TabView.vue')['default']
<<<<<<< HEAD
    WorldMapView: typeof import('./src/components/map/WorldMapView.vue')['default']
    WroldInfo: typeof import('./src/components/info/WroldInfo.vue')['default']
=======
    VanButton: typeof import('vant/es')['Button']
    VanSwipe: typeof import('vant/es')['Swipe']
    VanSwipeItem: typeof import('vant/es')['SwipeItem']
    WorldMapView: typeof import('./src/components/map/WorldMapView.vue')['default']
    WroldInfo: typeof import('./src/components/WroldInfo.vue')['default']
>>>>>>> fe33b65b667055bd0d038682577754640267fcd6
  }
}
